# information for running the gun but also for naming the file!
/control/alias PARTICLE anti_nu_mu
/control/alias ENERGY 300 #GeV
/control/alias NSHOTS 50 # How many times the gun is fired in a run
/control/alias DETECTOR MAIA # name the geometry you'd like to use


# This doesn't name the file, but it is useful for controlling the biasing
/control/alias TAUNUNUCBIASCC 1e11
/control/alias TAUNUNUCBIASNC 1
/control/alias TAUANUNUCBIASCC 1
/control/alias TAUANUNUCBIASNC 1
/control/alias MUNUNUCBIASCC 1e11
/control/alias MUNUNUCBIASNC 1
/control/alias MUANUNUCBIASCC 1e11
/control/alias MUANUNUCBIASNC 1
/control/alias ELNUNUCBIASCC 1e11
/control/alias ELNUNUCBIASNC 1
/control/alias ELANUNUCBIASCC 1
/control/alias ELANUNUCBIASNC 1
/control/alias NUELECCCBIAS 1
/control/alias NUELECNCBIAS 1

#______________________________________________________________________________
# /physics_lists/nu/NuDetectorName target
# Still need to define where the detector is so that we can define where the
# biasing is to happen. 

/detector/readGDML ../{DETECTOR}.gdml



/run/initialize
# Initializing the gun allows the worker threads to build the gun
# NB: Have to put gun commands after the initialize to run in multithreaded mode
/gun/particle {PARTICLE}
# sets our particle 
/gun/energy {ENERGY} GeV
# energy of the particles from the gun
/gun/position 0 0 0 cm
# gun position

# Allows dynamic filenaming, meaning we can assign unique runs unique names
# automatically based on their run parameters
/analysis/setFileName {PARTICLE}_{ENERGY}GeV_{NSHOTS}_{DETECTOR}

/custom/biasing/TauNuNucleusCcBias {TAUNUNUCBIASCC}
/custom/biasing/TauNuNucleusNcBias {TAUNUNUCBIASNC}
/custom/biasing/TauANuNucleusCcBias {TAUANUNUCBIASCC}
/custom/biasing/TauANuNucleusNcBias {TAUANUNUCBIASNC}
/custom/biasing/MuNuNucleusCcBias {MUNUNUCBIASCC}
/custom/biasing/MuNuNucleusNcBias {MUNUNUCBIASNC}
/custom/biasing/MuANuNucleusCcBias {MUANUNUCBIASCC}
/custom/biasing/MuANuNucleusNcBias {MUANUNUCBIASNC}
/custom/biasing/ElNuNucleusCcBias {ELNUNUCBIASCC}
/custom/biasing/ElNuNucleusNcBias {ELNUNUCBIASNC}
/custom/biasing/ElANuNucleusCcBias {ELANUNUCBIASCC}
/custom/biasing/ElANuNucleusNcBias {ELANUNUCBIASNC}
/custom/biasing/NuElectronCcBias {NUELECCCBIAS}
/custom/biasing/NuElectronNcBias {NUELECNCBIAS}
# This allows us to set biasing at runtime without the need to recompile the
# simulation code. It must be after the initialization of the run, otherwise the
# script will attempt to bias before the command to do so has been created.
/run/beamOn {NSHOTS}
